# Generated by Django 5.1.5 on 2025-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='google_map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Maps'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='house',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
