# Generated by Django 5.1.5 on 2025-01-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0003_networknode_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Долг перед поставщиком'),
        ),
    ]
