# Generated by Django 5.1.5 on 2025-01-31 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0004_alter_networknode_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='e_networks.contacts', verbose_name='Контакты'),
        ),
    ]
