# Generated by Django 5.1.5 on 2025-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0005_alter_networknode_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=255, verbose_name='Завод')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Лицензия подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'лицензия на производство',
                'verbose_name_plural': 'лицензии на производство',
            },
        ),
    ]
