# Generated by Django 5.1.5 on 2025-02-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0006_factorylicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorylicense',
            name='factory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='e_networks.networknode', verbose_name='Звено сети'),
        ),
    ]
