# Generated by Django 5.1.5 on 2025-02-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0009_remove_product_network_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(to='e_networks.product', verbose_name='Продукты'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
