# Generated by Django 5.1.5 on 2025-02-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_networks', '0010_remove_product_count_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='products',
            field=models.ManyToManyField(blank=True, to='e_networks.product', verbose_name='Продукты'),
        ),
        migrations.DeleteModel(
            name='FactoryLicense',
        ),
    ]
